extends Control

@onready var container = $ScrollContainer/HBoxContainer
# Preload the Node scene we just made
var node_scene = preload("res://Scenes/UI/MapNode.tscn")

func _ready():
	_generate_map_visuals()

func _generate_map_visuals():
	# Clear previous children (if any)
	for child in container.get_children():
		child.queue_free()
	
	# Loop through the data generated by RunManager
	for i in range(RunManager.tournament_map.size()):
		var data = RunManager.tournament_map[i]
		
		var node_instance = node_scene.instantiate()
		container.add_child(node_instance)
		
		# Setup the data
		node_instance.setup(data, i)
		node_instance.node_clicked.connect(_on_node_clicked)

	# --- NEW TIMING FIX ---
	# Wait exactly two frames for the HBoxContainer to finish organizing the sizes and positions
	await get_tree().process_frame
	await get_tree().process_frame
	
	_draw_connections()


# --- VISUAL FLUFF: CONNECTING LINES ---
func _draw_connections():
	var line = Line2D.new()
	line.width = 6 # Made slightly thicker for visibility
	line.default_color = Color(0.6, 0.6, 0.6) # Sleek gray line
	
	# --- NEW Z-INDEX FIX ---
	# Add the line to the container, then force it to the VERY TOP of the child list.
	# In Godot, the top of the list renders "first" (in the back), meaning it will
	# draw behind the nodes, but safely in front of your background!
	container.add_child(line)
	container.move_child(line, 0)
	
	for child_node in container.get_children():
		# Make sure we only draw points for the UI panels, not the line itself
		if child_node is Control and child_node != line:
			# Calculate the exact center of the node
			var center = child_node.position + (child_node.size / 2.0)
			line.add_point(center)

func _on_node_clicked(index: int):
	var data = RunManager.tournament_map[index]
	
	match data.type:
		MapNodeData.Type.FIGHT, MapNodeData.Type.BOSS:
			_start_fight(data)
		MapNodeData.Type.GYM:
			_enter_gym(data)

func _start_fight(data: MapNodeData):
	# 1. Setup Player Data (So P1 shows up on the left)
	# In Arcade Mode, the active player is stored in RunManager
	GameManager.next_match_p1_data = RunManager.player_run_data
	
	# 2. Setup Enemy Data (So P2 shows up on the right)
	# We take the enemy we generated for this specific map node
	GameManager.next_match_p2_data = data.enemy_data
	
	# 3. Transition to the VS Screen
	# This screen will play the animation and then automatically load the Battle
	SceneLoader.change_scene("res://Scenes/VsScreen.tscn")

func _enter_gym(_data: MapNodeData):
	print("Entering Gym...")
	# SceneLoader.change_scene("res://Scenes/Gym.tscn") 
	# (We haven't made this yet, so just print for now!)
